/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
 * DO NOT EDIT THIS FILE!! 
 * 
 *  TO CUSTOMIZE Block.js PLEASE EDIT ../custom/BlockCustom.js
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 * 
 */
const app = require('../../app.js');
const db_RapiDevKit_db = require('../../db/RapiDevKit_db_schema.js')
const properties = require('../../properties.js');
const handleError = require('../../security/util.js').handleError;
require('./custom/BlockCustom.js');

/*
 * SCHEMA DB Block
 * 
	{
		Actyve: {
			type: 'Boolean', 
			required : true
		},
		FontendAPIHook: {
			type: 'String'
		},
		Settings: {
			type: 'String'
		},
		//RELATIONS
		
		
		//EXTERNAL RELATIONS
		
		BlockType: {
			type: Schema.ObjectId,
			required : true,
			ref : "Block"
		},
		Privileges: {
			type: Schema.ObjectId,
			ref : "Block"
		},
		
	}
 * 
 */



//CRUD METHODS


/**
 * BlockService.create
 *   @description CRUD ACTION create
 *
 */
app.post(properties.api + '/blocks', function (req, res) {
	obj = new db_RapiDevKit_db.Block(req.body);
	obj.save(function (err) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * BlockService.delete
 *   @description CRUD ACTION delete
 *   @param ObjectId id Id
 *
 */
app['delete'](properties.api + '/blocks/:id', function (req, res) {
	db_RapiDevKit_db.Block.findByIdAndRemove(req.params.id, function (err) {
		  if (err) return handleError(err, res);
		  res.send(err);
	});
});

/**
 * BlockService.findByActyve
 *   @description CRUD ACTION findByActyve
 *   @param Objectid key Id of the resource Actyve to search
 *
 */
app.get(properties.api + '/blocks/findByActyve/:key', function (req, res) {

	db_RapiDevKit_db.Block.find({ 'Actyve' : req.params.key}).exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
	
});

/**
 * BlockService.findByBlockType
 *   @description CRUD ACTION findByBlockType
 *   @param Objectid key Id of the resource BlockType to search
 *
 */
app.get(properties.api + '/blocks/findByBlockType/:key', function (req, res) {

	db_RapiDevKit_db.Block.find({ 'BlockType' : req.params.key}).exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
	
});

/**
 * BlockService.findByFontendAPIHook
 *   @description CRUD ACTION findByFontendAPIHook
 *   @param Objectid key Id of the resource FontendAPIHook to search
 *
 */
app.get(properties.api + '/blocks/findByFontendAPIHook/:key', function (req, res) {

	db_RapiDevKit_db.Block.find({ 'FontendAPIHook' : req.params.key}).exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
	
});

/**
 * BlockService.get
 *   @description CRUD ACTION get
 *   @param ObjectId id Id 
 *
 */
app.get(properties.api + '/blocks/:id', function (req, res) {
	db_RapiDevKit_db.Block.findOne({_id:req.params.id}).exec(function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * BlockService.getBlockType
 *   @description CRUD ACTION getBlockType
 *   @param Objectid id ID of Block from BlockType
 *
 */
app.get(properties.api + '/blocks/:id/getBlockType', function (req, res) {

	db_RapiDevKit_db.Block.findOne({ _id : req.params.id})
	.populate("BlockType")
	.exec(function (err, obj) {
		if (err) return handleError(err, res);
		
		if(obj)
			res.send(obj.BlockType);
		else
			res.send();
	});
	
});

/**
 * BlockService.list
 *   @description CRUD ACTION list
 *
 */
app.get(properties.api + '/blocks', function (req, res) {
	db_RapiDevKit_db.Block.find().exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
});

/**
 * BlockService.update
 *   @description CRUD ACTION update
 *   @param ObjectId id Id
 *
 */
app.post(properties.api + '/blocks/:id', function (req, res) {
	db_RapiDevKit_db.Block.findByIdAndUpdate(req.params.id, req.body, {'new': true}, function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});


/*
 * CUSTOM SERVICES
 * 
 *	These services will be overwritten and implemented in  Custom.js
 */

