/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
 * DO NOT EDIT THIS FILE!! 
 * 
 *  TO CUSTOMIZE BlockType.js PLEASE EDIT ../custom/BlockTypeCustom.js
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 * 
 */
const app = require('../../app.js');
const db_RapiDevKit_db = require('../../db/RapiDevKit_db_schema.js')
const properties = require('../../properties.js');
const handleError = require('../../security/util.js').handleError;
require('./custom/BlockTypeCustom.js');

/*
 * SCHEMA DB BlockType
 * 
	{
		Code: {
			type: 'String'
		},
		Name: {
			type: 'String', 
			required : true
		},
		//RELATIONS
		
		
		//EXTERNAL RELATIONS
		
		BlockType: {
			type: Schema.ObjectId,
			required : true,
			ref : "Block"
		},
		ItemType: {
			type: Schema.ObjectId,
			required : true,
			ref : "BlockType"
		},
		
	}
 * 
 */



//CRUD METHODS


/**
 * BlockTypeService.create
 *   @description CRUD ACTION create
 *
 */
app.post(properties.api + '/blocktypes', function (req, res) {
	obj = new db_RapiDevKit_db.BlockType(req.body);
	obj.save(function (err) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * BlockTypeService.delete
 *   @description CRUD ACTION delete
 *   @param ObjectId id Id
 *
 */
app['delete'](properties.api + '/blocktypes/:id', function (req, res) {
	db_RapiDevKit_db.BlockType.findByIdAndRemove(req.params.id, function (err) {
		  if (err) return handleError(err, res);
		  res.send(err);
	});
});

/**
 * BlockTypeService.findByName
 *   @description CRUD ACTION findByName
 *   @param Objectid key Id of the resource Name to search
 *
 */
app.get(properties.api + '/blocktypes/findByName/:key', function (req, res) {

	db_RapiDevKit_db.BlockType.find({ 'Name' : req.params.key}).exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
	
});

/**
 * BlockTypeService.get
 *   @description CRUD ACTION get
 *   @param ObjectId id Id 
 *
 */
app.get(properties.api + '/blocktypes/:id', function (req, res) {
	db_RapiDevKit_db.BlockType.findOne({_id:req.params.id}).exec(function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * BlockTypeService.getItemType
 *   @description CRUD ACTION getItemType
 *   @param Objectid id ID of BlockType from ItemType
 *
 */
app.get(properties.api + '/blocktypes/:id/getItemType', function (req, res) {

	db_RapiDevKit_db.BlockType.findOne({ _id : req.params.id})
	.populate("ItemType")
	.exec(function (err, obj) {
		if (err) return handleError(err, res);
		
		if(obj)
			res.send(obj.ItemType);
		else
			res.send();
	});
	
});

/**
 * BlockTypeService.list
 *   @description CRUD ACTION list
 *
 */
app.get(properties.api + '/blocktypes', function (req, res) {
	db_RapiDevKit_db.BlockType.find().exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
});

/**
 * BlockTypeService.update
 *   @description CRUD ACTION update
 *   @param ObjectId id Id
 *
 */
app.post(properties.api + '/blocktypes/:id', function (req, res) {
	db_RapiDevKit_db.BlockType.findByIdAndUpdate(req.params.id, req.body, {'new': true}, function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});


/*
 * CUSTOM SERVICES
 * 
 *	These services will be overwritten and implemented in  Custom.js
 */

