/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
 * DO NOT EDIT THIS FILE!! 
 * 
 *  TO CUSTOMIZE ItemType.js PLEASE EDIT ../custom/ItemTypeCustom.js
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 * 
 */
const app = require('../../app.js');
const db_RapiDevKit_db = require('../../db/RapiDevKit_db_schema.js')
const properties = require('../../properties.js');
const handleError = require('../../security/util.js').handleError;
require('./custom/ItemTypeCustom.js');

/*
 * SCHEMA DB ItemType
 * 
	{
		Name: {
			type: 'String'
		},
		Schema: {
			type: 'String'
		},
		Validation: {
			type: 'String'
		},
		Visualization: {
			type: 'String'
		},
		//RELATIONS
		
		
		//EXTERNAL RELATIONS
		
		ItemType: {
			type: Schema.ObjectId,
			required : true,
			ref : "BlockType"
		},
		Type: {
			type: Schema.ObjectId,
			required : true,
			ref : "Item"
		},
		
	}
 * 
 */



//CRUD METHODS


/**
 * ItemTypeService.create
 *   @description CRUD ACTION create
 *
 */
app.post(properties.api + '/types', function (req, res) {
	obj = new db_RapiDevKit_db.ItemType(req.body);
	obj.save(function (err) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * ItemTypeService.delete
 *   @description CRUD ACTION delete
 *   @param ObjectId id Id
 *
 */
app['delete'](properties.api + '/types/:id', function (req, res) {
	db_RapiDevKit_db.ItemType.findByIdAndRemove(req.params.id, function (err) {
		  if (err) return handleError(err, res);
		  res.send(err);
	});
});

/**
 * ItemTypeService.findByName
 *   @description CRUD ACTION findByName
 *   @param Objectid key Id of the resource Name to search
 *
 */
app.get(properties.api + '/types/findByName/:key', function (req, res) {

	db_RapiDevKit_db.ItemType.find({ 'Name' : req.params.key}).exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
	
});

/**
 * ItemTypeService.get
 *   @description CRUD ACTION get
 *   @param ObjectId id Id 
 *
 */
app.get(properties.api + '/types/:id', function (req, res) {
	db_RapiDevKit_db.ItemType.findOne({_id:req.params.id}).exec(function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});

/**
 * ItemTypeService.list
 *   @description CRUD ACTION list
 *
 */
app.get(properties.api + '/types', function (req, res) {
	db_RapiDevKit_db.ItemType.find().exec(function (err, list) {
		if (err) return handleError(err, res);
		res.send(list);
	});
});

/**
 * ItemTypeService.update
 *   @description CRUD ACTION update
 *   @param ObjectId id Id
 *
 */
app.post(properties.api + '/types/:id', function (req, res) {
	db_RapiDevKit_db.ItemType.findByIdAndUpdate(req.params.id, req.body, {'new': true}, function (err, obj) {
		if (err) return handleError(err, res);
		res.send(obj);
	});
});


/*
 * CUSTOM SERVICES
 * 
 *	These services will be overwritten and implemented in  Custom.js
 */

